source :rubygems

gem 'bundler'
gem 'rake'
gem 'rack'
gem 'sinatra'
gem 'haml'
gem 'sass'
gem 'coffee-script'

group :production do
  gem 'therubyracer-heroku'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end
